# name: first workflow

# on: 
#     push:
#         branches:
#             -main
#     pull_request:
#         branches:
#             -main
#     workflow_dispatch:

# jobs: 
#     first-job: 
#         runs-on: ubuntu-latest
#         steps:
#             - name: print my name
#               run: echo "ITI"
