name: solar workflow

on: 
    push:
        branches:
            - main
            - 'feature/*'
    workflow_dispatch:

jobs: 
    unit-testing: 
        name: Unit Testing
        strategy:
            matrix:
                node_version: [18,20]
                operating_system: [ubuntu-latest, macos-latest]
        
        runs-on: ${{matrix.operating_system}}        
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.4.0
              with:
                node-version: ${{matrix.node_version}}

            - name: install npm
              run: npm install

            - name: unit testing runs
              run: npm test

            - uses: actions/upload-artifact@v4
              with:
                name: moch-test-result
                path: test-results.xml